-- Read-only installed-state expectations for the precise public facts consumed
-- or cleaned up by migrations 054-059.
WITH
expected_tables(table_name) AS (VALUES
  ('knowledge_current'), ('knowledge_edges'), ('knowledge_events'),
  ('message_deliveries'), ('private_reply_promotions'), ('profiles'),
  ('sessions'), ('space_members'), ('spaces'), ('voyage_members'), ('voyages')
),
expected_columns(table_name, column_name, type_name, not_null) AS (VALUES
  ('profiles', 'id', 'uuid', true),
  ('profiles', 'display_name', 'text', false),
  ('profiles', 'username', 'text', false),
  ('voyages', 'id', 'uuid', true),
  ('voyages', 'slug', 'text', true),
  ('voyages', 'invite_code', 'text', false),
  ('voyages', 'created_by', 'uuid', false),
  ('voyage_members', 'id', 'uuid', true),
  ('voyage_members', 'voyage_id', 'uuid', true),
  ('voyage_members', 'user_id', 'uuid', true),
  ('voyage_members', 'role', 'voyage_role', true),
  ('voyage_members', 'joined_at', 'timestamp with time zone', true),
  ('spaces', 'id', 'uuid', true),
  ('spaces', 'voyage_id', 'uuid', false),
  ('spaces', 'created_by', 'uuid', false),
  ('space_members', 'space_id', 'uuid', true),
  ('space_members', 'user_id', 'uuid', true),
  ('space_members', 'state', 'text', true),
  ('space_members', 'added_at', 'timestamp with time zone', true),
  ('sessions', 'id', 'uuid', true),
  ('sessions', 'user_id', 'uuid', false),
  ('sessions', 'status', 'session_status', true),
  ('sessions', 'voyage_id', 'uuid', false),
  ('sessions', 'space_id', 'uuid', false),
  ('sessions', 'last_message_at', 'timestamp with time zone', false),
  ('sessions', 'updated_at', 'timestamp with time zone', false),
  ('knowledge_events', 'id', 'uuid', true),
  ('knowledge_events', 'sequence_num', 'bigint', true),
  ('knowledge_events', 'user_id', 'uuid', false),
  ('knowledge_events', 'voyage_slug', 'text', false),
  ('knowledge_events', 'event_type', 'text', true),
  ('knowledge_events', 'content', 'text', false),
  ('knowledge_events', 'metadata', 'jsonb', false),
  ('knowledge_events', 'source_type', 'text', false),
  ('knowledge_events', 'source_ref', 'jsonb', false),
  ('knowledge_events', 'actor_id', 'uuid', false),
  ('knowledge_events', 'actor_type', 'text', true),
  ('knowledge_events', 'participants', 'uuid[]', false),
  ('knowledge_current', 'event_id', 'uuid', true),
  ('knowledge_current', 'user_id', 'uuid', false),
  ('knowledge_current', 'voyage_slug', 'text', false),
  ('knowledge_current', 'content', 'text', true),
  ('knowledge_current', 'embedding', 'vector(1536)', false),
  ('knowledge_current', 'participants', 'uuid[]', false),
  ('knowledge_current', 'event_type', 'text', false),
  ('knowledge_current', 'sender_display_name', 'text', false),
  ('knowledge_current', 'sender_user_id', 'uuid', false),
  ('knowledge_current', 'addressed_to', 'uuid[]', false),
  ('knowledge_current', 'attention_score', 'real', false),
  ('knowledge_current', 'search_vector', 'tsvector', false),
  ('knowledge_current', 'superseded_by', 'uuid', false),
  ('knowledge_current', 'base_attention', 'double precision', false),
  ('knowledge_current', 'promotion_count', 'integer', false),
  ('knowledge_edges', 'source_id', 'uuid', true),
  ('knowledge_edges', 'target_id', 'uuid', true),
  ('knowledge_edges', 'edge_type', 'text', true),
  ('private_reply_promotions', 'source_event_id', 'uuid', true),
  ('private_reply_promotions', 'sharer_user_id', 'uuid', true),
  ('private_reply_promotions', 'destination_space_id', 'uuid', true),
  ('private_reply_promotions', 'shared_event_id', 'uuid', true),
  ('message_deliveries', 'event_id', 'uuid', true),
  ('message_deliveries', 'recipient_user_id', 'uuid', true)
),
expected_enums(type_name, enum_values) AS (VALUES
  ('session_status', ARRAY['active', 'historical', 'archived']::text[]),
  ('voyage_role', ARRAY['captain', 'crew']::text[])
),
expected_defaults(table_name, column_name, default_expression) AS (VALUES
  ('knowledge_current', 'attention_score', '0.5'),
  ('space_members', 'state', '''active''::text')
),
expected_checks(table_name, check_expression) AS (VALUES
  ('space_members',
    '(state = ANY (ARRAY[''invited''::text, ''active''::text, ''left''::text]))')
),
expected_table_privileges(role_name, table_name, privilege_name) AS (VALUES
  ('service_role', 'spaces', 'SELECT'),
  ('service_role', 'voyage_members', 'SELECT'),
  ('service_role', 'space_members', 'SELECT'),
  ('service_role', 'space_members', 'INSERT'),
  ('service_role', 'space_members', 'UPDATE')
),
expected_triggers(
  table_name, trigger_name, function_name, trigger_type, enabled
) AS (VALUES
  ('knowledge_events', 'on_knowledge_event_insert',
    'apply_knowledge_event', 5::smallint, 'O'::"char")
),
expected_foreign_keys(
  table_name, constraint_name, columns, referenced_table, referenced_columns,
  delete_action, is_deferrable, is_deferred
) AS (VALUES
  ('private_reply_promotions', 'private_reply_promotions_source_event_id_fkey',
    ARRAY['source_event_id']::text[], 'knowledge_events', ARRAY['id']::text[],
    'r'::"char", false, false),
  ('private_reply_promotions', 'private_reply_promotions_sharer_user_id_fkey',
    ARRAY['sharer_user_id']::text[], 'profiles', ARRAY['id']::text[],
    'c'::"char", false, false),
  ('private_reply_promotions', 'private_reply_promotions_destination_space_id_fkey',
    ARRAY['destination_space_id']::text[], 'spaces', ARRAY['id']::text[],
    'c'::"char", false, false),
  ('private_reply_promotions', 'private_reply_promotions_shared_event_fkey',
    ARRAY['shared_event_id']::text[], 'knowledge_events', ARRAY['id']::text[],
    'r'::"char", true, true)
),
expected_functions(
  function_name, identity_arguments, security_definer,
  public_execute, anon_execute, authenticated_execute, service_execute
) AS (VALUES
  ('update_knowledge_embedding', 'uuid, vector', true, true, true, true, true),
  ('create_knowledge_event', 'text, text, uuid, text, jsonb, text, jsonb, uuid',
    true, true, true, true, true),
  ('get_knowledge_pending_embedding', 'integer', true, true, true, true, true),
  ('quiet_knowledge', 'uuid, text', true, true, true, true, true),
  ('pin_knowledge', 'uuid, text', true, true, true, true, true),
  ('search_knowledge',
    'vector, uuid, text, text[], double precision, integer, text, double precision, uuid[]',
    true, false, false, true, true),
  ('keyword_search', 'text, uuid, text, text, double precision, integer, uuid[]',
    false, true, true, true, true),
  ('scoped_knowledge_fetch',
    'uuid, text, uuid[], text, text, boolean, timestamp with time zone, timestamp with time zone, double precision, integer, uuid',
    false, true, true, true, true),
  ('graph_traverse',
    'uuid, text, text, integer, double precision, integer, uuid, text, uuid[]',
    false, false, false, false, true),
  ('get_or_create_active_session', 'uuid', true, true, true, true, true),
  ('get_resumable_sessions', 'uuid, integer', true, true, true, true, true),
  ('resume_session', 'uuid', true, true, true, true, true),
  ('transition_session', 'uuid, session_status', true, true, true, true, true),
  ('mark_session_extracted', 'uuid', true, true, true, true, true),
  ('set_session_title', 'uuid, text', true, true, true, true, true),
  ('create_voyage_with_captain', 'text, text, text, uuid',
    true, true, true, true, true),
  ('increment_promotion_count', 'uuid', true, true, true, true, true),
  ('promote_private_voyager_reply', 'uuid, uuid, uuid',
    true, false, false, false, true)
),
allowed_cleanup_functions(function_name, identity_arguments) AS (VALUES
  ('search_knowledge',
    'vector, uuid, text, boolean, text[], double precision, double precision, integer'),
  ('search_knowledge',
    'vector, uuid, text, boolean, text[], double precision, double precision, integer, text, double precision'),
  ('keyword_search', 'text, uuid, text, text, double precision, integer'),
  ('scoped_knowledge_fetch',
    'uuid, text, uuid[], text, text, boolean, timestamp with time zone, timestamp with time zone, double precision, integer'),
  ('resume_session', 'uuid, uuid'),
  ('search_memories', 'vector, uuid, double precision, integer'),
  ('supersede_memory', 'uuid, text, vector, double precision')
),
